<?php
$auctionList = $this->getListAuction();
// Zend_Debug::dump($auctionList); die();
if (count($auctionList) > 0):
    $_helper = $this->helper('catalog/output');
    $model = Mage::getModel('catalog/product');
    $modelAuction = Mage::getModel('auction/productauction');
    $delay = Mage::getStoreConfig('auction/general/delay_time');
    $now_time = Mage::getModel('core/date')->timestamp(time());
    ?>
    <script type="text/javascript"
            src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS), 'magestore/auction.js'; ?>"></script>
    <script type="text/javascript"
            src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS), 'magestore/auction210.js'; ?>"></script>
    <link rel="stylesheet" type="text/css"
          href="<?php echo $this->getSkinUrl('css/magestore/auction/featuredauction.css'); ?>" media="all"/>

    <div class="page-title category-title"><h1><?php echo $this->__('Auction Products') ?></h1></div>
    <ul class="products-grid row last odd">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i = 0;
        foreach ($auctionList as $item):
            $i++;
            $_product = $model->load($item->getId());
            // foreach ($_products->getItems() as $_product):
            ?>
            <?php if ($i++ % $_columnCount == 0): ?>

        <?php endif ?>
            <li class="item col-xs-3 <?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image"><img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>"
                        width="135" height="135" alt="<?php echo $this->escapeHtml($_product->getName()) ?>"/></a>

                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                            title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a>
                </h3>

                <div class="timeleft" id="timeleft_<?php echo $item->getId() ?>"></div>
                <div id="auction_info_<?php echo $item->getId() ?>">
                    <div class="row">
                        <center>
                                        <span class="current_price" id="current_price<?php echo $item->getId() ?>">
                                            <?php echo Mage::helper('core')->currency($currentPrice) ?>
                                        </span></center>
                        <div class="clear"></div>
                    </div>
                    <div class="row">
                        <center>
                                        <span class="bidder" id="bidder<?php echo $item->getId() ?>">
                                            <?php echo $lastBid ? $lastBid->getBidderName() : $this->__('None') ?>
                                        </span></center>
                        <div class="clear"></div>
                    </div>
                    <input type="hidden" id="codecolor<?php echo $item->getId() ?>" name="codecolor" value="0"/>
                    <input type="hidden" id="current_bid_id_<?php echo $item->getId() ?>"
                           value="<?php if ($lastBid) echo $lastBid->getId() ?>"/>
                </div>
                <div id="results_update_auction_<?php echo $item->getId() ?>" style="display:none;">
                </div>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
            </li>

        <?php endforeach; ?>
        <?php if ($i % $_columnCount == 0 || $i == count($_products)): ?>
    </ul>
<?php endif ?>

<?php endif; ?>

<block type="catalog/product_new" name="home.catalog.product.new" alias="product_new" template="catalog/product/new.phtml">
    <action method="setColumnCount"><columns>4</columns></action>
    <action method="setProductsCount"><count>8</count></action>
    <action method="addPriceBlockType"><type>bundle</type><block>bundle/catalog_product_price</block><template>bundle/catalog/product/price.phtml</template></action>
</block>
